#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "class.corelab.or.kr";
$SERVER_PORT = 8082;
$COURSE_NAME = "csapp";
$AUTOGRADE_TIMEOUT = 0;
1;
